#!/bin/sh
set -e

echo "###################################"
echo "# docker-postfix-legacy starting  #"
echo "###################################"

# ---- Timezone ----
if [ -n "$TZ" ]; then
    echo "# Timezone: $TZ"
    cp /usr/share/zoneinfo/"$TZ" /etc/localtime
    echo "$TZ" > /etc/timezone
fi

# ---- Generate main.cf from env vars (if no custom file mounted) ----
if [ ! -f /etc/postfix/main.cf.custom ]; then
    echo "# Generating main.cf from environment variables"

    SMTP_HOSTNAME="${SMTP_HOSTNAME:-localhost}"
    SMTP_DOMAIN="${SMTP_DOMAIN:-localdomain}"
    SMTP_RELAY_HOST="${SMTP_RELAY_HOST:-}"
    SMTP_RELAY_PORT="${SMTP_RELAY_PORT:-587}"
    SMTP_NETWORKS="${SMTP_NETWORKS:-127.0.0.0/8, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16}"
    SMTP_OUTBOUND_TLS="${SMTP_OUTBOUND_TLS:-encrypt}"
    SMTP_MESSAGE_SIZE="${SMTP_MESSAGE_SIZE:-52428800}"
    SMTP_LISTEN_PORT="${SMTP_LISTEN_PORT:-25}"

    cat > /etc/postfix/main.cf <<EOF
# Auto-generated by docker-postfix-legacy entrypoint
myhostname = ${SMTP_HOSTNAME}
mydomain = ${SMTP_DOMAIN}
myorigin = \$mydomain
smtp_helo_name = \$myhostname

inet_interfaces = all
inet_protocols = ipv4

mynetworks = ${SMTP_NETWORKS}
smtpd_relay_restrictions = permit_mynetworks, reject_unauth_destination
smtpd_recipient_restrictions = permit_mynetworks, reject_unauth_destination

# Inbound — no TLS, no auth (legacy device support)
smtpd_use_tls = no
smtpd_tls_security_level = none
smtpd_sasl_auth_enable = no

# Outbound — TLS + SASL auth to relay provider
smtp_tls_security_level = ${SMTP_OUTBOUND_TLS}
smtp_tls_wrappermode = no
smtp_sasl_auth_enable = yes
smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
smtp_sasl_security_options = noanonymous
smtp_sasl_tls_security_options = noanonymous

mydestination =
local_transport = error:local delivery disabled
alias_maps = hash:/etc/postfix/aliases
alias_database = hash:/etc/postfix/aliases

maillog_file = /dev/stdout

compatibility_level = 3.6
smtputf8_enable = no
recipient_delimiter = +
message_size_limit = ${SMTP_MESSAGE_SIZE}
EOF

    # Add relayhost if provided
    if [ -n "$SMTP_RELAY_HOST" ]; then
        echo "relayhost = [${SMTP_RELAY_HOST}]:${SMTP_RELAY_PORT}" >> /etc/postfix/main.cf
    fi
else
    echo "# Using custom mounted main.cf"
    cp /etc/postfix/main.cf.custom /etc/postfix/main.cf
fi

# ---- Generate sasl_passwd from env vars (if no file mounted) ----
if [ ! -f /etc/postfix/sasl_passwd ] && [ -n "$SMTP_RELAY_HOST" ] && [ -n "$SMTP_USERNAME" ]; then
    echo "# Generating sasl_passwd from environment variables"
    SMTP_PASSWORD="${SMTP_PASSWORD:-}"
    echo "[${SMTP_RELAY_HOST}]:${SMTP_RELAY_PORT} ${SMTP_USERNAME}:${SMTP_PASSWORD}" > /etc/postfix/sasl_passwd
fi

# ---- Hash map files ----
if [ -f /etc/postfix/sasl_passwd ]; then
    echo "# Hashing sasl_passwd"
    postmap /etc/postfix/sasl_passwd
    chmod 600 /etc/postfix/sasl_passwd
    [ -f /etc/postfix/sasl_passwd.db ] && chmod 600 /etc/postfix/sasl_passwd.db
else
    echo "# WARNING: No sasl_passwd — outbound auth will not work"
fi

if [ -f /etc/postfix/sender_relay ]; then
    echo "# Hashing sender_relay"
    postmap /etc/postfix/sender_relay
fi

if [ -f /etc/postfix/sender_sasl_passwd ]; then
    echo "# Hashing sender_sasl_passwd"
    postmap /etc/postfix/sender_sasl_passwd
    chmod 600 /etc/postfix/sender_sasl_passwd
    [ -f /etc/postfix/sender_sasl_passwd.db ] && chmod 600 /etc/postfix/sender_sasl_passwd.db
fi

# ---- Configure listen port ----
SMTP_LISTEN_PORT="${SMTP_LISTEN_PORT:-25}"
if [ "$SMTP_LISTEN_PORT" != "25" ]; then
    echo "# Configuring Postfix to listen on port ${SMTP_LISTEN_PORT}"
    sed -i "s/^smtp      inet/${SMTP_LISTEN_PORT}      inet/" /etc/postfix/master.cf
fi

# Rebuild aliases
postalias /etc/postfix/aliases 2>/dev/null || true

echo "# Starting Postfix in foreground"
exec postfix start-fg
