#!/bin/sh
set -e

echo "###################################"
echo "# docker-postfix-legacy starting  #"
echo "###################################"

# ---- Compatibility aliases (drop-in for other postfix-relay containers) ----
SMTP_RELAY_HOST="${SMTP_RELAY_HOST:-$RELAY_HOST}"
SMTP_RELAY_PORT="${SMTP_RELAY_PORT:-$RELAY_PORT}"
SMTP_USERNAME="${SMTP_USERNAME:-$RELAY_USER}"
SMTP_PASSWORD="${SMTP_PASSWORD:-$RELAY_PASS}"
SMTP_DOMAIN="${SMTP_DOMAIN:-$MYORIGIN}"
SMTP_NETWORKS="${SMTP_NETWORKS:-$MYNETWORKS}"

# ---- Timezone ----
if [ -n "$TZ" ]; then
    echo "# Timezone: $TZ"
    cp /usr/share/zoneinfo/"$TZ" /etc/localtime
    echo "$TZ" > /etc/timezone
fi

# ---- Generate main.cf from env vars (if no custom file mounted) ----
if [ ! -f /etc/postfix/main.cf.custom ]; then
    echo "# Generating main.cf from environment variables"

    SMTP_HOSTNAME="${SMTP_HOSTNAME:-localhost}"
    SMTP_DOMAIN="${SMTP_DOMAIN:-localdomain}"
    SMTP_RELAY_HOST="${SMTP_RELAY_HOST:-}"
    SMTP_RELAY_PORT="${SMTP_RELAY_PORT:-587}"
    SMTP_NETWORKS="${SMTP_NETWORKS:-127.0.0.0/8, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16}"
    SMTP_OUTBOUND_TLS="${SMTP_OUTBOUND_TLS:-encrypt}"
    SMTP_MESSAGE_SIZE="${SMTP_MESSAGE_SIZE:-52428800}"
    SMTP_LISTEN_PORT="${SMTP_LISTEN_PORT:-25}"

    cat > /etc/postfix/main.cf <<EOF
# Auto-generated by docker-postfix-legacy entrypoint
myhostname = ${SMTP_HOSTNAME}
mydomain = ${SMTP_DOMAIN}
myorigin = \$mydomain
smtp_helo_name = \$myhostname

inet_interfaces = all
inet_protocols = ipv4

mynetworks = ${SMTP_NETWORKS}

# Inbound: auth advertised but never required
# Legacy devices relay via mynetworks (no auth needed)
# Modern clients (Vaultwarden, etc.) can auth with PLAIN or LOGIN
smtpd_tls_security_level = none
smtpd_sasl_auth_enable = yes
smtpd_sasl_type = cyrus
smtpd_sasl_security_options = noanonymous
smtpd_sasl_tls_security_options = noanonymous
broken_sasl_auth_clients = yes

# permit_sasl_authenticated first so authed clients are always allowed;
# permit_mynetworks covers legacy devices that send no auth at all
smtpd_relay_restrictions = permit_sasl_authenticated, permit_mynetworks, reject_unauth_destination
smtpd_recipient_restrictions = permit_sasl_authenticated, permit_mynetworks, reject_unauth_destination

# Outbound — TLS + SASL auth to relay provider
smtp_tls_security_level = ${SMTP_OUTBOUND_TLS}
smtp_tls_wrappermode = no
smtp_sasl_auth_enable = yes
smtp_sasl_password_maps = lmdb:/etc/postfix/sasl_passwd
smtp_sasl_security_options = noanonymous
smtp_sasl_tls_security_options = noanonymous

mydestination =
local_transport = error:local delivery disabled
alias_maps = lmdb:/etc/postfix/aliases
alias_database = lmdb:/etc/postfix/aliases

maillog_file = /dev/stdout

compatibility_level = 3.6
smtputf8_enable = no
recipient_delimiter = +
message_size_limit = ${SMTP_MESSAGE_SIZE}
EOF

    # Add relayhost if provided
    if [ -n "$SMTP_RELAY_HOST" ]; then
        echo "relayhost = [${SMTP_RELAY_HOST}]:${SMTP_RELAY_PORT}" >> /etc/postfix/main.cf
    fi

    # Add sender rewriting if FROMADDRESS is set
    if [ -n "$FROMADDRESS" ]; then
        echo "# Configuring sender rewriting: ${FROMADDRESS}"

        # Rewrite envelope sender
        echo "smtp_generic_maps = lmdb:/etc/postfix/generic" >> /etc/postfix/main.cf
        printf '/.+/ %s\n' "${FROMADDRESS}" > /etc/postfix/generic
        postmap lmdb:/etc/postfix/generic

        # Step 1: At cleanup (ingest) time — capture original From: and prepend Reply-To:
        # This runs BEFORE smtp_header_checks so it sees the original From address
        echo "header_checks = pcre:/etc/postfix/header_checks_replyto" >> /etc/postfix/main.cf
        cat > /etc/postfix/header_checks_replyto <<'HEADEREOF'
/^From:\s+(.+)$/    PREPEND Reply-To: $1
HEADEREOF

        # Step 2: At smtp (outbound) time — replace From: header with FROMADDRESS
        # Also suppress any existing Reply-To that already equals FROMADDRESS to prevent duplicates
        echo "smtp_header_checks = pcre:/etc/postfix/header_checks_from" >> /etc/postfix/main.cf
        printf '/^From:\\s+(.+)$/    REPLACE From: %s\n' "${FROMADDRESS}" > /etc/postfix/header_checks_from
        printf '/^Reply-To:\\s+%s\\s*$/    IGNORE\n' "${FROMADDRESS}" >> /etc/postfix/header_checks_from

        echo "# Header rewriting configured"
    fi
else
    echo "# Using custom mounted main.cf"
    cp /etc/postfix/main.cf.custom /etc/postfix/main.cf
fi

# ---- Generate sasl_passwd from env vars (if no file mounted) ----
if [ ! -f /etc/postfix/sasl_passwd ] && [ -n "$SMTP_RELAY_HOST" ] && [ -n "$SMTP_USERNAME" ]; then
    echo "# Generating sasl_passwd from environment variables"
    SMTP_PASSWORD="${SMTP_PASSWORD:-}"
    echo "[${SMTP_RELAY_HOST}]:${SMTP_RELAY_PORT} ${SMTP_USERNAME}:${SMTP_PASSWORD}" > /etc/postfix/sasl_passwd
fi

# ---- Configure inbound SASL auth ----
# SMTP_AUTH_USERNAME / SMTP_AUTH_PASSWORD: credentials for clients connecting TO this relay
# (e.g. Vaultwarden, Gitea, Nextcloud). Separate from outbound relay credentials.
# Supports PLAIN and LOGIN — safe for internal use since this relay is not internet-facing.
# If not set, auth is still advertised but only mynetworks clients can relay (legacy behavior).
mkdir -p /etc/sasl2
cat > /etc/sasl2/smtpd.conf <<'SASLEOF'
pwcheck_method: auxprop
auxprop_plugin: sasldb
mech_list: PLAIN LOGIN
SASLEOF

if [ -n "$SMTP_AUTH_USERNAME" ] && [ -n "$SMTP_AUTH_PASSWORD" ]; then
    echo "# Configuring inbound SASL user: ${SMTP_AUTH_USERNAME}"
    echo "${SMTP_AUTH_PASSWORD}" | saslpasswd2 -p -c -u "${SMTP_HOSTNAME:-localhost}" "${SMTP_AUTH_USERNAME}"
    chown postfix:postfix /etc/sasldb2
    chmod 640 /etc/sasldb2
    echo "# Inbound SASL auth configured for ${SMTP_AUTH_USERNAME}"
else
    echo "# No SMTP_AUTH_USERNAME set — auth advertised, mynetworks relay only"
fi

# ---- Hash map files ----
if [ -f /etc/postfix/sasl_passwd ]; then
    echo "# Hashing sasl_passwd"
    postmap lmdb:/etc/postfix/sasl_passwd
    chmod 600 /etc/postfix/sasl_passwd
    [ -f /etc/postfix/sasl_passwd.lmdb ] && chmod 600 /etc/postfix/sasl_passwd.lmdb
else
    echo "# WARNING: No sasl_passwd — outbound auth will not work"
fi

if [ -f /etc/postfix/sender_relay ]; then
    echo "# Hashing sender_relay"
    postmap lmdb:/etc/postfix/sender_relay
fi

if [ -f /etc/postfix/sender_sasl_passwd ]; then
    echo "# Hashing sender_sasl_passwd"
    postmap lmdb:/etc/postfix/sender_sasl_passwd
    chmod 600 /etc/postfix/sender_sasl_passwd
    [ -f /etc/postfix/sender_sasl_passwd.lmdb ] && chmod 600 /etc/postfix/sender_sasl_passwd.lmdb
fi

# ---- Configure listen port ----
SMTP_LISTEN_PORT="${SMTP_LISTEN_PORT:-25}"
if [ "$SMTP_LISTEN_PORT" != "25" ]; then
    echo "# Configuring Postfix to listen on port ${SMTP_LISTEN_PORT}"
    sed -i "s/^smtp      inet/${SMTP_LISTEN_PORT}      inet/" /etc/postfix/master.cf
fi

# Rebuild aliases
postalias lmdb:/etc/postfix/aliases 2>/dev/null || true

# ---- Send test email after startup (background) ----
if [ -n "$TEST_EMAIL" ]; then
    (
        sleep 3
        echo "# Sending test email to ${TEST_EMAIL}"
        FROM="${FROMADDRESS:-postfix-legacy@${SMTP_DOMAIN:-localdomain}}"
        printf 'Subject: docker-postfix-legacy test\nFrom: %s\nTo: %s\n\nThis is a test email from docker-postfix-legacy.\nSent at: %s\n' \
            "${FROM}" "${TEST_EMAIL}" "$(date)" | sendmail -f "${FROM}" "${TEST_EMAIL}" && \
            echo "# Test email queued for ${TEST_EMAIL}" || \
            echo "# WARNING: Failed to queue test email"
    ) &
fi

echo "# Starting Postfix in foreground"
exec postfix start-fg
